kind: pipeline
name: default

steps:
- name: test
  image: node:10.16-alpine
  commands:
    - npm install
    - npm install codecov
    - test && codecov

- name: coverage
  image: plugins/codecov
  settings:
    token: 
      from_secret: codecov-token