kind: pipeline
name: default

steps:
- name: test
  image: node:10.16-alpine
  commands:
    - yarn install
    - yarn global add codecov
    - yarn build
    - yarn test && codecov

- name: set-commit-status
  image: gboo/github-status
  environment:
    GITHUB_TOKEN:
      from_secret: github_token
    GITHUB_STATUS_STATE: success
    GITHUB_STATUS_CONTEXT: drone/subtest

- name: coverage
  image: plugins/codecov
  settings:
    token: 
      from_secret: codecov-token
    paths:
      - ./coverage