kind: pipeline
name: default

steps:
- name: test
  image: node:10.16-alpine
  commands:
    - yarn install
    - yarn install codecov -g
    - yarn test && codecov

- name: coverage
  image: plugins/codecov
  settings:
    token: 
      from_secret: codecov-token
    paths:
      - ./coverage