kind: pipeline
name: default

steps:
- name: lint
  image: node:10.16
  commands:
    - yarn install
    - ./ci/lint.sh
  environment:
    GITHUB_TOKEN:
      from_secret: github_token

- name: test
  image: node:10.16-alpine
  commands:
    - yarn install
    - yarn global add codecov
    - yarn build
    - yarn test && codecov

- name: coverage
  image: plugins/codecov
  settings:
    token: 
      from_secret: codecov-token
    paths:
      - ./coverage