name: Yarn Test
on: [push]

jobs:
  test:
    name: Run Yarn Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          version: "10.16"
      - run: npm install
      - run: npm test
